# docker-compose.override.yml
# This file extends docker-compose.yml for development

version: '3.8'

services:
  nginx:
    container_name: escashop_nginx_dev
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - escashop_network_dev
    depends_on:
      - backend
      - frontend
    command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  escashop_network_dev:
    driver: bridge
