name: Visual Regression Testing

on:
  push:
    branches: [ dependency-testing ]
  pull_request:
    branches: [ dependency-testing ]

jobs:
  percy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm install
    - name: Run Visual Tests with Percy
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      run: |
        npm run test:visual
    - name: Upload Percy Screenshots
      uses: actions/upload-artifact@v4
      with:
        name: Percy Screenshots
        path: ./screenshots
